---
hand_closing_subspace:
  "wamslashbhandslashfinger_1slashdist_joint": &DISTCLOSING 0.33333
  'wamslashbhandslashfinger_2slashdist_joint': *DISTCLOSING
  'wamslashbhandslashfinger_3slashdist_joint': *DISTCLOSING
  'wamslashbhandslashfinger_1slashmed_joint': &MEDCLOSING 1
  'wamslashbhandslashfinger_2slashmed_joint': *MEDCLOSING
  'wamslashbhandslashfinger_3slashmed_joint': *MEDCLOSING
  'wamslashbhandslashfinger_1slashprox_joint': 0
  'wamslashbhandslashfinger_2slashprox_joint': 0


hand_closed_angle: 2

hand_preshape_subspace: 
  wamslashbhandslashfinger_1slashdist_joint: 0
  wamslashbhandslashfinger_2slashdist_joint: 0
  wamslashbhandslashfinger_3slashdist_joint: 0
  wamslashbhandslashfinger_1slashmed_joint: 0
  wamslashbhandslashfinger_2slashmed_joint: 0
  wamslashbhandslashfinger_3slashmed_joint: 0
  wamslashbhandslashfinger_1slashprox_joint: 1
  wamslashbhandslashfinger_2slashprox_joint: 1


graspit_joint_order:
  - wamslashbhandslashfinger_1slashprox_joint
  - wamslashbhandslashfinger_1slashmed_joint
  - wamslashbhandslashfinger_2slashmed_joint
  - wamslashbhandslashfinger_3slashmed_joint



hand_joint_order:
  - wam/bhand/finger_1/med_joint
  - wam/bhand/finger_2/med_joint
  - wam/bhand/finger_3/med_joint
  - wam/bhand/finger_1/prox_joint

# joint_mimic:  
#   wamslashbhandslashfinger_1slashmed_joint:
#     ratio: 1
#     source: wamslashbhandslashfinger_1slashmed_joint
#   wamslashbhandslashfinger_2slashmed_joint:
#     ratio: 1
#     source: wamslashbhandslashfinger_2slashmed_joint
#   wamslashbhandslashfinger_3slashmed_joint:
#     ratio: 1
#     source: wamslashbhandslashfinger_3slashmed_joint
#   wamslashbhandslashfinger_1slashdist_joint:
#     ratio: *DISTCLOSING
#     source: wamslashbhandslashfinger_1slashmed_joint
#   wamslashbhandslashfinger_2slashdist_joint:
#     ratio: *DISTCLOSING
#     source: wamslashbhandslashfinger_2slashmed_joint
#   wamslashbhandslashfinger_3slashdist_joint:
#     ratio: *DISTCLOSING
#     source: wamslashbhandslashfinger_3slashmed_joint
#   wamslashbhandslashfinger_2slashprox_joint:
#     ratio: 1
#     source: wamslashbhandslashfinger_1slashprox_joint

approach_dir_x: 0
approach_dir_y: 0
approach_dir_z: 1

end_effector_name: BarrettHand

grasp_executer/planner_config_name: '[SBLkConfigDefault]'
grasp_analyzer/planner_config_name: '[PRMkConfigDefault]'
trajectory_action_name: '/setFollowTrajectory'
hand_manager: 'grasp_execution_helpers.barret_manager'