---
hand_closing_subspace:
  l_gripper_joint: 0

hand_closed_angle: 0

hand_preshape_subspace:
  l_gripper_joint: 0


hand_joint_order:
  - l_gripper_joint

home_joint_values: [0, 0, 0, 0, 0, 0, 0]

approach_dir_x: 0
approach_dir_y: 0
approach_dir_z: 1

arm_name: 'left_arm'
end_effector_name: left_gripper

grasp_executer/planner_config_name: '[SBLkConfigDefault2]'
grasp_analyzer/planner_config_name: '[PRMkConfigDefault]'

trajectory_action_name: '/l_arm_controller/follow_joint_trajectory'
hand_manager: 'grasp_execution_helpers.pr2_manager'
gripper_action_name: '/l_gripper_controller/gripper_action'
home_arm_pose_name: 'home_left'

execution_stages: ['PreshapeHand', 'MoveToPreGraspPosition', 'PreshapeHand', 'Approach', 'CloseHand', 'Lift']
